script: ./travis-build.sh
jdk:
- oraclejdk8
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: JVA8aVHDyGKv+zaODWH8eVYxVynHQpiMqWvA9FWORU6xYYjMhKFhrKz7ZMHS/oVUyBYI0aBX+uybbm03ZQcdY+bL/l/2vwt35BVx+gFPtq6VSPygwITRUZcrvYB8YXgBKaBP7usGfDjXPsIuAUm9Pqpvb3E572hA16TWncmjr0Y=
