script: "./travis-build.sh"
jdk:
- oraclejdk8
- openjdk11
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: p1aKLY22iAl6jdRG4zSHdt5dgH2LvUUkrjD0goocwhrBBbcsKoBVFQ20jrPxNkkegkrwlq6AWDi5bKGNTgfICjZjq89IV9iuvrqMQ3XlFDWOnT/BDZC+hw7h6giAV1kukTUEBNqWAGbijvj26mOulX1vyVkewEH638c5FU0rXrs=
  - secure: oJAJSLp/cEdMZPq/peu0sB02khuGPG7aTNRuJWu+7mjhYdjpG2x18G3a1jjHaF180wxVh53bBAgFlX+hNKq54xA449r6JhaQ9ckJWPkm1yNxVt15aD2lmGXZeafpIUWSYKxy5az3YErcTaRMVL6qPkVA5ZUi3FOBDCOwBiS5G7k=
  - secure: JK77fd+vxjk4SKw5pPtTinKVvR1KQYIIW1MC4eAk+Xyl4joFsCs7iyFR7DG00THvStcAr3+58dMmIyPWSwWZbb/jjVZqoQdIYn/40z1MWWslODztN1e7gXW9aqBRbUJgrc/akEUnRmwRX0ispkBXuZkCWMINez89q6AHlE4jNkA=
